openapi: 3.0.3
info:
  title: Invoices API
  description: Invoice data endpoints for clinic billing mobile application dashboard financial metrics
  version: 1.0.0
  contact:
    name: Clinic Billing API Team

servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://api.clinicbilling.com/api/v1
    description: Production server (placeholder)

tags:
  - name: invoices
    description: Invoice operations

paths:
  /invoices/:
    get:
      tags:
        - invoices
      summary: List all invoices
      description: Retrieve a list of all invoices for financial metrics calculation. Returns array of invoice objects with payment status and amounts.
      operationId: listInvoices
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response - array of invoices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice'
              example:
                - id: 1
                  invoice_number: "INV-2024-001"
                  patient_id: 42
                  total_amount_cents: 15000
                  status: "paid"
                  created_at: "2024-01-15T10:30:00Z"
                  updated_at: "2024-01-16T14:20:00Z"
                  currency: "USD"
                  due_date: "2024-01-30T00:00:00Z"
                  paid_at: "2024-01-16T14:20:00Z"
                - id: 2
                  invoice_number: "INV-2024-002"
                  patient_id: 43
                  total_amount_cents: 8500
                  status: "pending"
                  created_at: "2024-01-20T09:15:00Z"
                  updated_at: "2024-01-20T09:15:00Z"
                  currency: "USD"
                  due_date: "2024-02-05T00:00:00Z"
                - id: 3
                  invoice_number: "INV-2024-003"
                  patient_id: 44
                  total_amount_cents: 23000
                  status: "unpaid"
                  created_at: "2024-01-25T11:00:00Z"
                  updated_at: "2024-01-25T11:00:00Z"
                  currency: "USD"
                  due_date: "2024-02-10T00:00:00Z"
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Invalid authentication credentials"
        '403':
          description: Forbidden - token valid but insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Insufficient permissions to access invoices"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Internal server error"
        '503':
          description: Service unavailable - backend temporarily unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Service temporarily unavailable"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token in Authorization header (Bearer {token})

  schemas:
    Invoice:
      type: object
      required:
        - id
        - invoice_number
        - patient_id
        - total_amount_cents
        - status
      properties:
        id:
          type: integer
          format: int64
          description: Unique invoice identifier
          minimum: 1
          example: 1
        invoice_number:
          type: string
          description: Human-readable invoice number
          minLength: 1
          example: "INV-2024-001"
        patient_id:
          type: integer
          format: int64
          description: Associated patient identifier
          minimum: 1
          example: 42
        total_amount_cents:
          type: integer
          description: Invoice amount in cents (can be negative for refunds/credits)
          example: 15000
        status:
          type: string
          description: Payment status of the invoice
          enum:
            - paid
            - unpaid
            - pending
          example: "paid"
          # Note: API may return other status values (e.g., cancelled, refunded)
          # Frontend should handle gracefully
        created_at:
          type: string
          format: date-time
          description: Invoice creation timestamp (ISO 8601)
          example: "2024-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (ISO 8601)
          example: "2024-01-16T14:20:00Z"
        currency:
          type: string
          description: Currency code (ISO 4217 format)
          pattern: '^[A-Z]{3}$'
          example: "USD"
        due_date:
          type: string
          format: date-time
          description: Invoice due date (ISO 8601)
          example: "2024-01-30T00:00:00Z"
        paid_at:
          type: string
          format: date-time
          description: Payment completion timestamp (ISO 8601, typically only for paid invoices)
          example: "2024-01-16T14:20:00Z"
      additionalProperties: true
      # Note: API may include additional fields not defined here
      # Frontend should ignore unknown fields gracefully

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Invalid authentication credentials"
      additionalProperties: false

