openapi: 3.0.3
info:
  title: Audit Log API
  description: Audit log endpoints for clinic billing mobile application to track system actions and user activities
  version: 1.0.0
  contact:
    name: Clinic Billing API Team

servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://api.clinicbilling.com/api/v1
    description: Production server (placeholder)

tags:
  - name: audit
    description: Audit log operations

paths:
  /audit/:
    get:
      tags:
        - audit
      summary: List all audit log entries
      description: Retrieve a list of all audit log entries. Returns array of audit log entry objects with actor, action, target, and timestamp information.
      operationId: listAuditLogs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response - array of audit log entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditLogEntry'
              example:
                - id: "1"
                  actor_type: "user"
                  actor_id: 42
                  action: "create"
                  target_type: "invoice"
                  target_id: 123
                  details:
                    invoice_number: "INV-2024-001"
                    amount_cents: 15000
                  created_at: "2024-12-19T14:30:00Z"
                - id: "2"
                  actor_type: "user"
                  actor_id: 43
                  action: "view"
                  target_type: "patient"
                  target_id: 567
                  details: null
                  created_at: "2024-12-19T13:15:00Z"
                - id: "3"
                  actor_type: "system"
                  actor_id: "automation"
                  action: "send"
                  target_type: "invoice"
                  target_id: 124
                  details:
                    refund_id: "REF-123"
                    amount_cents: 5000
                  created_at: "2024-12-19T12:00:00Z"
                - id: "4"
                  actor_type: "user"
                  actor_id: 44
                  action: "delete"
                  target_type: "payment"
                  target_id: 789
                  details:
                    reason: "Cancelled transaction"
                  created_at: "2024-12-19T11:00:00Z"
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Invalid authentication credentials"
        '403':
          description: Forbidden - token valid but insufficient permissions to view audit logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Insufficient permissions to access audit logs"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Internal server error"
        '503':
          description: Service unavailable - backend temporarily unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Service temporarily unavailable"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token in Authorization header (Bearer {token})

  schemas:
    AuditLogEntry:
      type: object
      required:
        - id
        - actor_type
        - actor_id
        - action
        - target_type
        - target_id
        - created_at
      properties:
        id:
          oneOf:
            - type: string
            - type: integer
          description: Unique audit log entry identifier
          example: "1"
        actor_type:
          type: string
          description: Type of entity that performed the action
          minLength: 1
          example: "user"
          # Common values: "user", "system", "api", "automation"
          # Frontend should handle any string value gracefully
        actor_id:
          oneOf:
            - type: string
            - type: integer
          description: Identifier of the actor
          example: 42
        action:
          type: string
          description: Action performed
          minLength: 1
          example: "create"
          # Common values: "create", "update", "delete", "view", "send", "generate", "login", "logout"
          # Frontend should handle any string value gracefully
        target_type:
          type: string
          description: Type of entity that was acted upon
          minLength: 1
          example: "invoice"
          # Common values: "invoice", "patient", "payment", "appointment"
          # Frontend should handle any string value gracefully
        target_id:
          oneOf:
            - type: string
            - type: integer
          description: Identifier of the target resource
          example: 123
        details:
          oneOf:
            - type: object
            - type: "null"
          description: Additional contextual information about the action
          nullable: true
          additionalProperties: true
          # Details object structure varies by action type
          # Common fields: refund_id (string), amount (number in cents), invoice_id (number), invoice_number (string)
          # Frontend should parse details flexibly and handle missing fields
          example:
            refund_id: "REF-123"
            amount_cents: 5000
            invoice_number: "INV-2024-001"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the action occurred (ISO 8601)
          example: "2024-12-19T14:30:00Z"
      additionalProperties: false
      # Note: API response must match this structure
      # Frontend should handle missing required fields gracefully (skip entry, log warning)

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Invalid authentication credentials"
      additionalProperties: false

